# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12W__h-4aQ8bKpoROldXxqcdyIdb40x3-

# Proyek Akhir: Sistem Rekomendasi Buku

## 1. Pendahuluan

Dalam era digital yang penuh dengan informasi, pengguna sering kesulitan menemukan buku yang sesuai minat mereka.  
Proyek ini mengimplementasikan sistem rekomendasi buku berbasis Content-Based Filtering dan Collaborative Filtering  dengan menggunakan data dari komunitas Book-Crossing untuk membantu menyajikan rekomendasi yang lebih relevan.

**Sumber Dataset :** [Kumpulan Data Rekomendasi Buku](https://www.kaggle.com/datasets/arashnic/book-recommendation-dataset)

## 2. Import Library

Pada tahap ini dilakukan import library yang diperlukan untuk analisis data, visualisasi, dan pemodelan machine learning.
"""

# Import Pustaka
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from scipy.sparse.linalg import svds
import os

import zipfile
from google.colab import files
from google.colab import drive

"""Muat dataset dari Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""## 3. Ekstraksi ZIP Dataset"""

zip_path = "/content/drive/MyDrive/Proyek Akhir MLT/Dataset.zip"
extract_path = "dataset"

if not os.path.exists(extract_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Dataset berhasil diekstrak.")
else:
    print("Folder sudah ada, tidak perlu ekstrak ulang.")

"""## Cek isi folder

Menampilkan isi folder dataset untuk memastikan file telah berhasil diekstrak dan tersedia untuk diproses.
"""

path_kelas = "/content/dataset"
print("Isi dalam dataset:")
print(os.listdir(path_kelas))

"""## 4. Data Understanding

Memulai tahap pemahaman data dengan menentukan lokasi file dataset dan menampilkan informasi awal dari masing-masing file (Books, Ratings, Users).
"""

print("\n--- Memulai Tahap Data Understanding ---")

# Lokasi dataset
dataset_path = "/content/dataset"
books_file = os.path.join(dataset_path, "Books.csv")
ratings_file = os.path.join(dataset_path, "Ratings.csv")
users_file = os.path.join(dataset_path, "Users.csv")

"""### Memuat dataset

Membaca file CSV ke dalam DataFrame pandas. Jika terjadi error pada encoding, mencoba encoding alternatif. Menampilkan info dan contoh data dari masing-masing dataset.
"""

print(f"Memuat dataset dari {dataset_path}...")
try:
    # Menggunakan kutip tunggal standar, tanpa backslash escape
    books = pd.read_csv(books_file, encoding='latin-1', low_memory=False, on_bad_lines='skip')
    ratings = pd.read_csv(ratings_file, encoding='latin-1', on_bad_lines='skip')
    users = pd.read_csv(users_file, encoding='latin-1', on_bad_lines='skip')
    print("Dataset berhasil dimuat.")
except FileNotFoundError:
    print(f"Error: Pastikan file Books.csv, Ratings.csv, dan Users.csv ada di direktori {dataset_path}")
    exit()
except Exception as e:
    print(f"Terjadi error saat memuat dataset: {e}")
    # Mencoba encoding lain jika latin-1 gagal total
    try:
        print("Mencoba memuat dengan encoding cp1252...")
        books = pd.read_csv(books_file, encoding='cp1252', low_memory=False, on_bad_lines='skip')
        ratings = pd.read_csv(ratings_file, encoding='cp1252', on_bad_lines='skip')
        users = pd.read_csv(users_file, encoding='cp1252', on_bad_lines='skip')
        print("Dataset berhasil dimuat dengan encoding cp1252.")
    except Exception as e2:
        print(f"Gagal memuat dataset dengan encoding alternatif: {e2}")
        exit()

"""### Tampilkan informasi awal dataset"""

print("\nInformasi Dataset Books:")
books.info()
print("\nContoh Data Books:")
print(books.head())

print("\nInformasi Dataset Ratings:")
ratings.info()
print("\nContoh Data Ratings:")
print(ratings.head())

print("\nInformasi Dataset Users:")
users.info()
print("\nContoh Data Users:")
print(users.head())

"""### EDA & Visualisasi

#### Cek missing values

Melakukan pengecekan jumlah nilai yang hilang (missing values) pada setiap kolom di ketiga dataset.
"""

print("\nJumlah Missing Values per Kolom:")
print("Books:\n", books.isnull().sum())
print("\nRatings:\n", ratings.isnull().sum())
print("\nUsers:\n", users.isnull().sum())

"""#### Cek duplikat

Melakukan pengecekan jumlah data duplikat pada setiap dataset berdasarkan kolom kunci.
"""

print("\nJumlah Duplikat:")
print("Books (berdasarkan ISBN):", books.duplicated(subset='ISBN').sum())
print("Ratings (berdasarkan User-ID dan ISBN):", ratings.duplicated(subset=['User-ID', 'ISBN']).sum())
print("Users (berdasarkan User-ID):", users.duplicated(subset='User-ID').sum())

"""#### Eksplorasi Data Ratings

Menampilkan distribusi nilai rating buku untuk mengetahui sebaran rating yang diberikan pengguna.
"""

print("\nDistribusi Book-Rating:")
rating_counts = ratings['Book-Rating'].value_counts().sort_index()
print(rating_counts)

"""#### Visualisasi Distribusi Rating (Simpan ke file)

Membuat visualisasi distribusi rating buku dan menyimpannya ke file gambar.
"""

plt.figure(figsize=(10, 5))
sns.countplot(data=ratings, x='Book-Rating')
plt.title('Distribusi Book Ratings')
plt.xlabel('Rating')
plt.ylabel('Jumlah')
plt.grid(axis='y', linestyle='--')

# Simpan ke file
rating_dist_path = "/content/dataset/Ratings.png"
plt.savefig(rating_dist_path)
print(f"Visualisasi distribusi rating disimpan di: {rating_dist_path}")

# Tampilkan ke layar
plt.show()

# Tutup plot agar tidak membebani memori
plt.close()

"""#### Eksplorasi Data Users (Age)

Menampilkan statistik deskriptif kolom usia pengguna untuk mengetahui rentang dan sebaran usia.
"""

print("\nStatistik Deskriptif Kolom Age:")
print(users['Age'].describe())

"""#### Mengatasi nilai usia yang tidak realistis

Membersihkan data usia dengan hanya mengambil pengguna berusia antara 5 hingga 100 tahun.
"""

users_cleaned_age = users[(users['Age'] >= 5) & (users['Age'] <= 100)]

"""#### Visualisasi Distribusi Usia Pengguna (Setelah Cleaning)

Membuat visualisasi distribusi usia pengguna setelah data dibersihkan dan menyimpannya ke file gambar.
"""

plt.figure(figsize=(10, 5))
sns.histplot(users_cleaned_age['Age'], bins=30, kde=True)
plt.title('Distribusi Usia Pengguna (5-100 tahun)')
plt.xlabel('Usia')
plt.ylabel('Jumlah')

# Simpan ke file
age_dist_path = "/content/dataset/age_distribution.png"
plt.savefig(age_dist_path)
print(f"Visualisasi distribusi usia disimpan di: {age_dist_path}")

# Tampilkan grafik di notebook
plt.show()

# Tutup plot
plt.close()

"""#### Eksplorasi Data Books (Year-Of-Publication)

Memeriksa tipe data dan contoh nilai unik pada kolom tahun terbit buku.
"""

print("\nMemeriksa Kolom Year-Of-Publication:")
print("Tipe data awal:", books['Year-Of-Publication'].dtype)
print("Contoh nilai unik:", books['Year-Of-Publication'].unique()[:20])

"""#### Konversi ke numerik

Mengonversi kolom tahun terbit ke tipe numerik dan mengecek jumlah nilai NaN setelah konversi.
"""

books['Year-Of-Publication'] = pd.to_numeric(books['Year-Of-Publication'], errors='coerce')

# Cek nilai NaN setelah konversi
print("Jumlah NaN setelah konversi:", books['Year-Of-Publication'].isnull().sum())

"""#### Mengatasi tahun yang tidak valid

Membersihkan data tahun terbit dengan hanya mengambil tahun yang valid (lebih dari 0 dan tidak melebihi tahun sekarang).
"""

current_year = pd.Timestamp.now().year
books_cleaned_year = books[(books['Year-Of-Publication'] > 0) & (books['Year-Of-Publication'] <= current_year)]

"""#### Visualisasi Distribusi Tahun Publikasi (Setelah Cleaning)

Membuat visualisasi distribusi tahun terbit buku setelah data dibersihkan dan menyimpannya ke file gambar.
"""

plt.figure(figsize=(12, 6))
sns.histplot(books_cleaned_year['Year-Of-Publication'], bins=50, kde=False)
plt.title('Distribusi Tahun Publikasi Buku (Valid)')
plt.xlabel('Tahun Publikasi')
plt.ylabel('Jumlah Buku')
plt.xlim(books_cleaned_year['Year-Of-Publication'].min(), current_year)

# Simpan ke file
year_dist_path = "/content/dataset/year_distribution.png"
plt.savefig(year_dist_path)
print(f"Visualisasi distribusi tahun publikasi disimpan di: {year_dist_path}")

# Tampilkan grafik di notebook
plt.show()

# Tutup plot
plt.close()

"""## 5. Data Preparation

*   Menggabungkan data ratings dengan data buku untuk memudahkan proses modeling.   
*   Melakukan pengecekan dan penanganan missing values pada kolom penting.
*   Melakukan filtering data untuk mengurangi sparsity, yaitu hanya mengambil buku dengan minimal 10 rating dan pengguna dengan minimal 5 rating.

Menggabungkan data ratings dengan data buku
"""

print("Menggabungkan data ratings dan books...")
df = ratings.merge(books, on='ISBN', how='left')

"""Cek missing values setelah merge"""

print("Missing values setelah merge:\n", df.isnull().sum())

"""### Penanganan Missing Values"""

print("Mengisi missing values pada Book-Author dan Publisher dengan 'Unknown'...")
df['Book-Author'].fillna('Unknown', inplace=True)
df['Publisher'].fillna('Unknown', inplace=True)

"""Mengatasi sparsity data pada Collaborative Filtering"""

min_book_ratings = 10
min_user_ratings = 5

print(f"Jumlah data awal: {len(df)}")

"""### Filter buku"""

book_rating_counts = df['ISBN'].value_counts()
df = df[df['ISBN'].isin(book_rating_counts[book_rating_counts >= min_book_ratings].index)]
print(f"Jumlah data setelah filter buku (min {min_book_ratings} ratings): {len(df)}")

"""### Filter pengguna"""

user_rating_counts = df['User-ID'].value_counts()
df = df[df['User-ID'].isin(user_rating_counts[user_rating_counts >= min_user_ratings].index)]
print(f"Jumlah data setelah filter pengguna (min {min_user_ratings} ratings): {len(df)}")

"""#### Cek ulang dimensi data setelah filtering

Menampilkan jumlah pengguna dan buku unik setelah proses filtering untuk memastikan data sudah lebih bersih dan manageable.
"""

print(f"Jumlah pengguna unik setelah filter: {df['User-ID'].nunique()}")
print(f"Jumlah buku unik setelah filter: {df['ISBN'].nunique()}")

# Reset index
df.reset_index(drop=True, inplace=True)

"""## 6. Modeling - Content-Based Filtering

*   Mengambil data buku unik hasil preparation, sampling jika data terlalu besar.  
*   Menggabungkan fitur teks (author dan publisher) untuk digunakan sebagai fitur content-based.
*   Membuat matriks TF-IDF dari fitur gabungan, menghitung cosine similarity antar buku, dan membuat mapping ISBN ke index.  
*   Menyediakan fungsi rekomendasi buku berbasis kemiripan konten.

Menggunakan data buku unik setelah preparation
"""

books_prepared_full = df.drop_duplicates(subset='ISBN').reset_index(drop=True)
print(f"Jumlah buku unik awal untuk Content-Based: {len(books_prepared_full)}")

"""Penyesuaian Resource: Menggunakan Sampel Data"""

sample_size_books_cb = 5000
if len(books_prepared_full) > sample_size_books_cb:
    print(f"Mengambil sampel {sample_size_books_cb} buku untuk Content-Based Filtering karena keterbatasan resource.")
    books_prepared = books_prepared_full.sample(n=sample_size_books_cb, random_state=42).reset_index(drop=True)
else:
    print("Ukuran data buku unik sudah cukup kecil, menggunakan semua data.")
    books_prepared = books_prepared_full

print(f"Jumlah buku unik yang digunakan untuk Content-Based (setelah sampling): {len(books_prepared)}")

"""#### Menggabungkan fitur teks"""

books_prepared['content_features'] = books_prepared['Book-Author'] + ' ' + books_prepared['Publisher']

"""Pastikan semua konten dalam format string dan isi NaN dengan string kosong"""

books_prepared['content_features'] = books_prepared['content_features'].fillna('').astype(str)

"""Inisialisasi TF-IDF Vectorizer"""

tfidf = TfidfVectorizer(stop_words='english')

# Fit and transform
print("Membuat matriks TF-IDF...")
tfidf_matrix = tfidf.fit_transform(books_prepared['content_features'])

"""Menghitung Cosine Similarity"""

print("Menghitung cosine similarity...")
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print("Shape matriks cosine similarity:", cosine_sim.shape)

"""Membuat mapping ISBN ke index"""

isbn_to_index = pd.Series(books_prepared.index, index=books_prepared['ISBN'])

"""#### Fungsi rekomendasi Content-Based"""

def get_content_based_recommendations(isbn, top_n=10):
    if isbn not in isbn_to_index:
        if isbn in books_prepared_full['ISBN'].values:
            try:
                book_full_features = books_prepared_full[books_prepared_full['ISBN'] == isbn]['content_features'].iloc[0]
                input_vector = tfidf.transform([book_full_features])
                sim_scores_input = cosine_similarity(input_vector, tfidf_matrix).flatten()
                sim_indices = sim_scores_input.argsort()[::-1][:top_n]
                recommendations = books_prepared.iloc[sim_indices][['ISBN', 'Book-Title', 'Book-Author', 'Publisher']].copy()
                recommendations['Similarity_Score'] = sim_scores_input[sim_indices]
                return recommendations
            except Exception as e:
                return f"Gagal mendapatkan rekomendasi untuk ISBN {isbn} (tidak di sampel): {e}"
        else:
            return f"ISBN {isbn} tidak ditemukan dalam data asli maupun sampel."

    idx = isbn_to_index[isbn]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    book_indices = [i[0] for i in sim_scores]
    recommendations = books_prepared.iloc[book_indices][['ISBN', 'Book-Title', 'Book-Author', 'Publisher']].copy()
    recommendations['Similarity_Score'] = [s[1] for s in sim_scores]
    return recommendations

"""## Contoh penggunaan

Menampilkan contoh hasil rekomendasi buku berdasarkan ISBN tertentu menggunakan pendekatan content-based.
"""

if not df.empty:
    example_isbn_cb = df['ISBN'].iloc[0]
    print(f"\nContoh Rekomendasi Content-Based untuk ISBN: {example_isbn_cb}")
    recommendations_cb = get_content_based_recommendations(example_isbn_cb)
    print(recommendations_cb)
else:
    print("\nDataFrame df kosong, tidak dapat mengambil contoh ISBN.")

"""## 7. Modeling - Collaborative Filtering

*   Menggunakan data rating eksplisit (rating > 0) dan melakukan sampling pengguna serta buku jika data terlalu besar.
*   Membuat user-item matrix, melakukan SVD untuk dekomposisi matriks, dan membangun fungsi rekomendasi berbasis prediksi rating hasil SVD.

Menggunakan rating eksplisit (rating > 0)
"""

df_explicit_full = df[df['Book-Rating'] > 0].copy()

"""Penyesuaian Resource: Menggunakan Sampel Data (Pengguna & Buku)

#### Ambil sampel pengguna
"""

max_users_cf = 5000
all_user_ids = df_explicit_full['User-ID'].unique()
if len(all_user_ids) > max_users_cf:
    print(f"Mengambil sampel {max_users_cf} pengguna untuk Collaborative Filtering karena keterbatasan resource.")
    sampled_user_ids = np.random.choice(all_user_ids, max_users_cf, replace=False)
    df_explicit = df_explicit_full[df_explicit_full['User-ID'].isin(sampled_user_ids)]
else:
    print("Jumlah pengguna sudah cukup kecil, menggunakan semua pengguna.")
    df_explicit = df_explicit_full

# Ambil sampel buku (berdasarkan rating dari pengguna sampel)
max_books_cf = 5000
all_isbn_ids_sampled_users = df_explicit['ISBN'].unique()
if len(all_isbn_ids_sampled_users) > max_books_cf:
    print(f"Mengambil sampel {max_books_cf} buku (dari pengguna sampel) untuk Collaborative Filtering.")
    sampled_isbn_ids = np.random.choice(all_isbn_ids_sampled_users, max_books_cf, replace=False)
    df_explicit = df_explicit[df_explicit['ISBN'].isin(sampled_isbn_ids)]
else:
    print("Jumlah buku (dari pengguna sampel) sudah cukup kecil, menggunakan semua buku.")

print(f"Jumlah data rating setelah sampling pengguna & buku: {len(df_explicit)}")

"""Buat mapping User-ID dan ISBN ke integer index (untuk data sampel CF)"""

user_ids_cf = df_explicit['User-ID'].unique()
user_id_map_cf = {id: i for i, id in enumerate(user_ids_cf)}
df_explicit['user_idx'] = df_explicit['User-ID'].map(user_id_map_cf)

isbn_ids_cf = df_explicit['ISBN'].unique()
isbn_id_map_cf = {id: i for i, id in enumerate(isbn_ids_cf)}
isbn_map_reverse_cf = {i: id for i, id in enumerate(isbn_ids_cf)}
df_explicit['isbn_idx'] = df_explicit['ISBN'].map(isbn_id_map_cf)

print(f"Jumlah pengguna unik (setelah sampling CF): {df_explicit['user_idx'].nunique()}")
print(f"Jumlah buku unik (setelah sampling CF): {df_explicit['isbn_idx'].nunique()}")

"""Membuat pivot table (user-item matrix) dari data sampel CF"""

print("Membuat User-Item Interaction Matrix (dari data sampel CF)...")
try:
    user_item_matrix = df_explicit.pivot_table(index='user_idx', columns='isbn_idx', values='Book-Rating').fillna(0)
except MemoryError:
    print("Error: Masih terjadi MemoryError saat membuat pivot table. Coba kurangi max_users_cf atau max_books_cf.")
    exit()
except Exception as e:
    print(f"Error saat membuat pivot table: {e}")
    exit()

"""Konversi ke numpy array"""

user_item_matrix_np = user_item_matrix.values

"""Tambahan: Normalisasi dengan mengurangi rata-rata user

Melakukan Singular Value Decomposition (SVD)
"""

k = 50
print(f"Melakukan SVD dengan k={k}...")
try:
    # Pastikan k tidak lebih besar dari dimensi matriks
    k_svd = min(k, user_item_matrix_np.shape[0] - 1, user_item_matrix_np.shape[1] - 1)
    if k_svd < 1:
        raise ValueError("Dimensi matriks terlalu kecil untuk SVD setelah sampling.")
    print(f"Menggunakan k={k_svd} untuk SVD.")
    U, sigma, Vt = svds(user_item_matrix_np, k=k_svd)
except ValueError as ve:
    print(f"Error saat melakukan SVD: {ve}")
    U, sigma, Vt = None, None, None # Tandai gagal
except Exception as e:
    print(f"Error tidak terduga saat SVD: {e}")
    U, sigma, Vt = None, None, None # Tandai gagal

"""Lanjutkan hanya jika SVD berhasil"""

if U is not None:
    # Memprediksi semua rating
    sigma_diag_matrix = np.diag(sigma)
    all_user_predicted_ratings = np.dot(np.dot(U, sigma_diag_matrix), Vt)

    # Buat DataFrame dari hasil prediksi rating
    preds_df = pd.DataFrame(all_user_predicted_ratings, index=user_item_matrix.index, columns=user_item_matrix.columns)

    # Fungsi rekomendasi Collaborative Filtering (SVD)
    def get_collaborative_svd_recommendations(user_id, top_n=10):
        if user_id not in user_id_map_cf:
            if user_id in df_explicit_full['User-ID'].unique():
                return f"User-ID {user_id} ada di data asli, tetapi tidak termasuk dalam sampel pengguna untuk CF."
            else:
                return f"User-ID {user_id} tidak ditemukan dalam data rating eksplisit asli."

        user_idx = user_id_map_cf[user_id]

        if user_idx not in preds_df.index:
             return f"Internal Error: User index {user_idx} tidak ditemukan di matriks prediksi."

        predicted_ratings_row = preds_df.loc[user_idx]

        if user_idx in user_item_matrix.index:
            rated_isbn_indices = user_item_matrix.loc[user_idx][user_item_matrix.loc[user_idx] > 0].index
        else:
            rated_isbn_indices = pd.Index([])

        predicted_ratings_unrated = predicted_ratings_row.drop(rated_isbn_indices, errors='ignore')
        top_indices = predicted_ratings_unrated.nlargest(top_n).index
        recommended_isbns = [isbn_map_reverse_cf[idx] for idx in top_indices]

        recommended_books = books_prepared_full[books_prepared_full['ISBN'].isin(recommended_isbns)].drop_duplicates(subset='ISBN')

        recommendations = recommended_books[['ISBN', 'Book-Title', 'Book-Author', 'Publisher']].copy()
        pred_scores = predicted_ratings_unrated[top_indices].to_dict()
        recommendations['Predicted_Rating'] = recommendations['ISBN'].map(lambda x: pred_scores.get(isbn_id_map_cf.get(x)))
        recommendations.dropna(subset=['Predicted_Rating'], inplace=True)
        recommendations = recommendations.sort_values(by='Predicted_Rating', ascending=False)

        return recommendations

"""## Contoh penggunaan (pilih satu User-ID dari data sampel CF)

Menampilkan contoh hasil rekomendasi buku untuk salah satu User-ID menggunakan pendekatan collaborative filtering (SVD).
"""

if not df_explicit.empty:
        example_user_id_cf = df_explicit['User-ID'].iloc[0]
        print(f"\nContoh Rekomendasi Collaborative Filtering (SVD) untuk User-ID (dari sampel): {example_user_id_cf}")
        recommendations_cf = get_collaborative_svd_recommendations(example_user_id_cf)
        print(recommendations_cf)
    else:
        print("\nDataFrame df_explicit (setelah sampling CF) kosong, tidak dapat mengambil contoh User-ID.")

"""## 8. Evaluation

Menghitung dan menampilkan nilai RMSE (Root Mean Squared Error) dari hasil prediksi SVD pada data training (sampel CF) untuk mengukur performa model collaborative filtering.

Evaluasi SVD menggunakan RMSE pada data training (sampel CF)
"""

from sklearn.metrics import mean_squared_error

mask = user_item_matrix_np > 0
original_ratings = user_item_matrix_np[mask]
predicted_ratings = all_user_predicted_ratings[mask]

if len(original_ratings) > 0:
    rmse = np.sqrt(mean_squared_error(original_ratings, predicted_ratings))
    print(f"\nRMSE (Root Mean Squared Error) SVD pada data training (sampel CF): {rmse:.4f}")
else:
    print("\nTidak ada rating asli > 0 dalam matriks sampel CF untuk menghitung RMSE.")