# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVDA8oZTV19emgUqmUHlTDX9Ky6kkXG7

# Klasifikasi Persetujuan Pinjaman Berdasarkan Profil Risiko Finansial

## 1. Pendahuluan

Permohonan pinjaman seringkali memerlukan proses evaluasi risiko yang cermat. Proyek ini bertujuan membangun model machine learning untuk memprediksi apakah permohonan pinjaman akan **disetujui** atau **tidak**, berdasarkan profil demografis dan kondisi finansial pemohon.

**Sumber data:**  
[Financial Risk for Loan Approval (Kaggle)](https://www.kaggle.com/datasets/lorenzozoppelletto/financial-risk-for-loan-approval)

## 2. Import Library

Pada tahap ini dilakukan import library yang diperlukan untuk analisis data, visualisasi, dan pemodelan machine learning.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             confusion_matrix, classification_report, roc_auc_score, RocCurveDisplay)
from imblearn.over_sampling import SMOTE

"""Muat dataset dari Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""## 3. Data Understanding

### 3.1. Load Dataset & Preview

Dataset diambil dari Google Drive agar dapat digunakan untuk proses analisis selanjutnya.
"""

# Baca dataset
path = "/content/drive/MyDrive/Proyek pertama MLT/Loan.csv"
df = pd.read_csv(path)

"""### 3.2. Preview Data

Menampilkan beberapa baris pertama dari dataset untuk melihat struktur dan tipe data.
"""

# Preview data
print("Data Preview:")
display(df.head())

"""### 3.3. Info Dataset

Menampilkan informasi tipe data dan jumlah non-null pada setiap kolom.
"""

# Info data
print("\nDataset Info:")
df.info()

"""### 3.4. Cek Missing Values

Melakukan pengecekan missing values pada setiap kolom dataset.
"""

# Cek missing values
print("\nMissing Values:")
print(df.isnull().sum())

"""### 3.5. Mengecek Duplikasi

Mengecek jumlah baris duplikat pada dataset
"""

duplikat = df.duplicated().sum()
print(f"Jumlah baris duplikat: {duplikat}")

"""### 3.6. Mengecek Outlier

Menggunakan boxplot untuk fitur numerik utama.
"""

# Contoh boxplot untuk AnnualIncome dan CreditScore
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
sns.boxplot(y=df['AnnualIncome'])
plt.title('Boxplot AnnualIncome')
plt.subplot(1,2,2)
sns.boxplot(y=df['CreditScore'])
plt.title('Boxplot CreditScore')
plt.show()

"""### 3.7. Penjelasan Fitur

Dataset terdiri dari 20.000 data pemohon pinjaman dengan fitur demografi, keuangan, dan histori kredit.  
**Target:** `LoanApproved` (1 = Disetujui, 0 = Tidak Disetujui)

**Fitur yang digunakan:**  
- Age, MaritalStatus, NumberOfDependents, EducationLevel, EmploymentStatus, JobTenure  
- AnnualIncome, MonthlyIncome, SavingsAccountBalance, CheckingAccountBalance, TotalAssets, TotalLiabilities, NetWorth, MonthlyDebtPayments, DebtToIncomeRatio, TotalDebtToIncomeRatio, CreditCardUtilizationRate  
- CreditScore, LoanAmount, LoanDuration, HomeOwnershipStatus, NumberOfOpenCreditLines, NumberOfCreditInquiries, PreviousLoanDefaults, PaymentHistory, BankruptcyHistory, LengthOfCreditHistory, LoanPurpose, BaseInterestRate, InterestRate, MonthlyLoanPayment

**Fitur yang tidak digunakan:**  
- ApplicationDate, RiskScore (tidak relevan untuk prediksi awal persetujuan)

## 4. Data Preparation

Pada tahap ini dilakukan pemilihan fitur, pengecekan distribusi target, dan penanganan missing value.

### 4.1. Pilih Fitur & Cek Distribusi Target

Memilih fitur yang direkomendasikan dan menampilkan distribusi target.
"""

# Pilih fitur yang direkomendasikan
selected_features = [
    'Age', 'MaritalStatus', 'NumberOfDependents', 'EducationLevel', 'EmploymentStatus', 'JobTenure',
    'AnnualIncome', 'MonthlyIncome', 'SavingsAccountBalance', 'CheckingAccountBalance', 'TotalAssets',
    'TotalLiabilities', 'NetWorth', 'MonthlyDebtPayments', 'DebtToIncomeRatio', 'TotalDebtToIncomeRatio',
    'CreditCardUtilizationRate', 'CreditScore', 'LoanAmount', 'LoanDuration', 'HomeOwnershipStatus',
    'NumberOfOpenCreditLines', 'NumberOfCreditInquiries', 'PreviousLoanDefaults', 'PaymentHistory',
    'BankruptcyHistory', 'LengthOfCreditHistory', 'LoanPurpose', 'BaseInterestRate', 'InterestRate',
    'MonthlyLoanPayment'
]

# Pastikan semua kolom ada
missing_cols = [col for col in selected_features if col not in df.columns]
if missing_cols:
    print("Kolom berikut tidak ditemukan:", missing_cols)

# Ambil fitur dan target
X = df[selected_features]
y = df['LoanApproved']

"""#### Visualisasi Distribusi Target

Visualisasi distribusi target untuk melihat apakah data imbalance.
"""

# Cek distribusi target
print("Distribusi Target (LoanApproved):")
print(y.value_counts(normalize=True))

# Visualisasi distribusi target
plt.figure(figsize=(5,3))
sns.countplot(x=y)
plt.title('Distribusi Target LoanApproved')
plt.xlabel('LoanApproved')
plt.ylabel('Count')
plt.show()

"""**Insight:**  
Distribusi target sedikit imbalance, sehingga perlu dipertimbangkan penyeimbangan kelas pada tahap modeling.

### 4.2. Penanganan Missing Value

Melakukan imputasi missing value pada fitur numerik dan kategorikal.
"""

# Cek missing value pada fitur terpilih
print(X.isnull().sum())

# Imputasi sederhana: numerik dengan median, kategorikal dengan modus
# Imputasi numerik
for col in X.select_dtypes(include=['float64', 'int64']).columns:
    X[col] = X[col].fillna(X[col].median())

# Imputasi kategorikal
for col in X.select_dtypes(include=['object']).columns:
    X[col] = X[col].fillna(X[col].mode()[0])

"""### 4.3. Split Data Train-Test

Data dibagi menjadi 80% train dan 20% test, stratified berdasarkan target.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

"""### 4.4. Preprocessing Pipeline

Membuat pipeline preprocessing untuk fitur numerik dan kategorikal, serta menyiapkan SMOTE untuk penyeimbangan kelas.
"""

# Identifikasi fitur numerik & kategorikal
numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object']).columns.tolist()

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# SMOTE untuk penyeimbangan kelas
smote = SMOTE(random_state=42)

"""## 5. Modeling

Kita akan membandingkan dua model:  
- Logistic Regression  
- Random Forest Classifier

Pipeline: Preprocessing → SMOTE → Model

### 5.1. Inisialisasi Model

Membuat pipeline untuk dua model: Logistic Regression dan Random Forest.
"""

models = {
    'Logistic Regression': Pipeline([
        ('preprocessor', preprocessor),
        ('smote', smote),
        ('classifier', LogisticRegression(random_state=42, max_iter=1000))
    ]),
    'Random Forest': Pipeline([
        ('preprocessor', preprocessor),
        ('smote', smote),
        ('classifier', RandomForestClassifier(random_state=42))
    ])
}

"""### 5.2. Training & Evaluation

Melatih model dan mengevaluasi performa menggunakan metrik klasifikasi.

Kita evaluasi dengan metrik: Accuracy, Precision, Recall, F1, ROC-AUC, dan Confusion Matrix.
"""

results = {}
y_preds = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_preds[name] = y_pred

    print(f"\n{name} Classification Report:")
    print(classification_report(y_test, y_pred))

    results[name] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1-Score': f1_score(y_test, y_pred),
        'ROC AUC': roc_auc_score(y_test, model.predict_proba(X_test)[:,1])
    }

# Tabel perbandingan metrik
results_df = pd.DataFrame(results).T
print("\nPerbandingan Performa Model:")
display(results_df)

"""**Insight:**  
Dari hasil evaluasi, model Logistic Regression memiliki F1-Score dan ROC-AUC yang lebih tinggi dibanding Random Forest, sehingga lebih direkomendasikan untuk kasus ini.

### 5.3. Confusion Matrix & ROC Curve

Visualisasi confusion matrix dan ROC curve untuk kedua model.
"""

from sklearn.metrics import ConfusionMatrixDisplay

for name, y_pred in y_preds.items():
    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    plt.title(f'Confusion Matrix - {name}')
    plt.show()

plt.figure(figsize=(8,6))
for name, model in models.items():
    RocCurveDisplay.from_estimator(model, X_test, y_test, name=name)
plt.plot([0, 1], [0, 1], 'k--')
plt.title('ROC Curve Comparison')
plt.show()

"""### 5.4. Feature Importance (Random Forest)

Menampilkan 10 fitur terpenting dari model Random Forest.
"""

# Feature importance hanya untuk Random Forest
rf_model = models['Random Forest']
rf_model.fit(X_train, y_train)
# Ambil nama fitur setelah one-hot encoding
ohe = rf_model.named_steps['preprocessor'].named_transformers_['cat']
cat_feature_names = ohe.get_feature_names_out(categorical_features)
all_feature_names = numeric_features + list(cat_feature_names)
importances = rf_model.named_steps['classifier'].feature_importances_

# Visualisasi 10 fitur terpenting
feat_imp = pd.Series(importances, index=all_feature_names).sort_values(ascending=False)[:10]
plt.figure(figsize=(8,4))
sns.barplot(x=feat_imp.values, y=feat_imp.index)
plt.title('Top 10 Feature Importance (Random Forest)')
plt.xlabel('Importance')
plt.show()

"""**Insight:**  
Fitur yang paling berpengaruh dalam prediksi persetujuan pinjaman berdasarkan hasil dari model Random Forest adalah:

  - TotalDebtToIncomeRatio – Rasio total utang terhadap pendapatan memiliki pengaruh paling besar terhadap hasil prediksi.
  - MonthlyIncome – Pendapatan bulanan juga sangat penting dalam menentukan keputusan persetujuan.
  - AnnualIncome – Pendapatan tahunan turut menjadi salah satu faktor penentu utama.

Ketiga fitur ini menunjukkan bahwa profil pendapatan dan kemampuan debitur dalam mengelola utangnya menjadi faktor krusial dalam evaluasi kelayakan pinjaman.

### 5.5. Feature Importance (Logistic Regression)

Menampilkan pengaruh fitur terhadap prediksi berdasarkan koefisien model Logistic Regression.
"""

# Ambil model logistic regression yang sudah fit
lr_model = models['Logistic Regression']
lr_model.fit(X_train, y_train)

# Ambil nama fitur setelah one-hot encoding
ohe = lr_model.named_steps['preprocessor'].named_transformers_['cat']
cat_feature_names = ohe.get_feature_names_out(categorical_features)
all_feature_names = numeric_features + list(cat_feature_names)

# Koefisien model
coefs = lr_model.named_steps['classifier'].coef_[0]
feat_imp_lr = pd.Series(coefs, index=all_feature_names).sort_values(key=abs, ascending=False)[:10]

plt.figure(figsize=(8,4))
sns.barplot(x=feat_imp_lr.values, y=feat_imp_lr.index)
plt.title('Top 10 Feature Importance (Logistic Regression)')
plt.xlabel('Coefficient Value')
plt.show()

"""**Insight:**

Fitur yang paling berpengaruh dalam prediksi persetujuan pinjaman berdasarkan hasil dari model Logistic Regression adalah:

  - TotalDebtToIncomeRatio – Memiliki pengaruh negatif paling besar, artinya semakin tinggi rasio utang terhadap pendapatan, semakin kecil kemungkinan pinjaman disetujui.
  - InterestRate – Juga berpengaruh negatif, menunjukkan bahwa bunga pinjaman yang lebih tinggi cenderung mengurangi kemungkinan persetujuan.
  - MonthlyIncome – Memberikan pengaruh positif yang kuat; semakin tinggi pendapatan bulanan, semakin besar kemungkinan pinjaman disetujui.

Insight ini menunjukkan bahwa kestabilan keuangan pemohon sangat menentukan hasil evaluasi, terutama dalam hal rasio utang, tingkat pendapatan, dan bunga pinjaman yang diajukan.

## 6. Hasil Klasifikasi (Contoh Output)

Berikut contoh hasil prediksi model pada 10 data uji:
"""

hasil_klasifikasi = pd.DataFrame({
    'Index': X_test.index,
    'Label Asli': y_test.values,
    'Prediksi Logistic Regression': y_preds['Logistic Regression'],
    'Prediksi Random Forest': y_preds['Random Forest']
})
print(hasil_klasifikasi.head(10))

"""## 7. Kesimpulan

- Berdasarkan hasil evaluasi, Logistic Regression merupakan model terbaik untuk prediksi persetujuan pinjaman pada dataset ini, karena memiliki nilai F1-Score dan ROC-AUC yang lebih tinggi dibandingkan Random Forest.

- Model Logistic Regression mampu mengklasifikasikan data dengan baik, ditunjukkan oleh nilai akurasi, presisi, recall, dan F1-Score yang tinggi.

- Visualisasi confusion matrix dan ROC curve menunjukkan performa model yang stabil dan kemampuannya dalam membedakan kelas dengan baik.

- Analisis feature importance pada Logistic Regression menunjukkan bahwa fitur-fitur seperti TotalDebtToIncomeRatio, InterestRate, dan MonthlyIncome memiliki pengaruh paling besar terhadap keputusan persetujuan pinjaman. Fitur-fitur ini mencerminkan kondisi keuangan peminjam dan kemampuannya dalam membayar kembali pinjaman.

- Model ini dapat digunakan sebagai alat bantu dalam proses seleksi awal persetujuan pinjaman, namun tetap diperlukan evaluasi dan pengujian lebih lanjut sebelum diterapkan pada data riil atau sistem produksi.
"""